---
# tasks file for scenarion-scheduler

- name: relabel nodes with right labels
  run_once: true
  shell: oc label nodes node1.example.com node2.example.com node3.example.com region=workers --overwrite

- name: relabel nodes with right labels
  run_once: true
  shell: "{{ item }}"
  with_items:
  - "oc label nodes node1.example.com zone=az1 --overwrite"
  - "oc label nodes node2.example.com zone=az2 --overwrite"
  - "oc label nodes node3.example.com zone=az3 --overwrite"
  - "oc label node infra1.example.com zone=az1 --overwrite"
  - "oc label node infra2.example.com zone=az2 --overwrite"
  - "oc label node infra3.example.com zone=az3 --overwrite"

- name: delete scheduler project
  run_once: true
  shell: oc delete project scheduler

