scripts:
  - name: "Scenario 0 - ETCD Failure"
    description: "Observe ETCD state and recover when quorum is lost. Simulate 2 DC deployment."
    executor: 
      path: "/usr/share/ansible/summit/"
      script: make
      actionmapper:
        solve: s0-solve
        recover1: s0-start-etcd2
        recover2: s0-start-etcd3
        init: "s0-stop-etcd2 s0-stop-etcd3"
        break1: s0-stop-etcd2
        break2: s0-stop-etcd3
    actions: "[init, solve, break1, break2]"
  - name: "scenario 1 - ETCD"
    description: "Observe ETCD - Bonus task"
    executor: 
      path: "/usr/share/ansible/summit/"
      script: make
      actionmapper:
        init: s1-start
        solve: s1-solve
    actions: "[init, solve]"
  - name: "scenario 2 - Failed builds, application storage issues"
    description: "Inspect failed build and solve why they are failed. "
    executor: 
      path: "/usr/share/ansible/summit/"
      script: make
      actionmapper:
        init: s2-start
        solve: s2-solve
    actions: "[init, solve]"
  - name: "scenario 3 - Scheduler issues"
    description: "Inspect broken scheduler and solve pod distribution issue."
    executor: 
      path: "/usr/share/ansible/summit/"
      script: make
      actionmapper:
        init: s3-start
        solve: s3-solve
    actions: "[init, solve]"
  - name: "scenario 4 - Debugging application"
    description: "Debug failed application using oc client"
    executor: 
      path: "/usr/share/ansible/summit/"
      script: make
      actionmapper:
        init: s4-start
        solve: s4-solve
    actions: "[init, solve]"
  - name: "scenario 5 - SDN failures "
    description: "Observe and solve OVS/SDN network failures"
    executor: 
      path: "/usr/share/ansible/summit/"
      script: make
      actionmapper:
        init: s5-start
        solve: s5-solve
    actions: "[init, solve]"
  - name: "scenario 6 - DNS failures "
    description: "Observe and DNS config failures"
    executor: 
      path: "/usr/share/ansible/summit/"
      script: make
      actionmapper:
        init: s6-start
        solve: s6-solve
    actions: "[init, solve]"
