---
- hosts: all:!bastion
  roles:
   - lib_utils
   - lib_openshift
   - ansible-rh-subscription-manager
   - ansible-docker
   - ocp-pre-hooks
   - iptables-prom

- hosts: masters
  roles:
   - ocp-pre-hooks-masters
