---
- hosts: nodes
  roles:
   - lib_openshift
   - lib_utils
  post_tasks:
   - name: Stop dnsmasq in node1 compute node.
     service:
       name: dnsmasq
       state: stopped
     when: inventory_hostname == groups.nodes[0]
