---
- name: Ensure IPtables rule exists
  shell: "{{ item }}"
  with_items:
  - "iptables -I INPUT -p tcp -m tcp --dport 8443 -j ACCEPT"
  - "iptables -I INPUT -p tcp -m tcp --dport 9100 -j ACCEPT"
  - "iptables -I INPUT -p tcp -m tcp --dport 2379 -j ACCEPT"
  - "iptables-save > /etc/sysconfig/iptables"

- name: Ensure IPtables is restarted
  systemd:
    state: restarted
    name: iptables
