---
# tasks file for ocp-pre-hooks

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ ocp_pre_packages }}"

# # cat /etc/cron.d/sysstat
# Run system activity accounting tool every 10 minutes
# */5 * * * * root /usr/lib64/sa/sa1 1 1
# 0 * * * * root /usr/lib64/sa/sa1 600 6 &
# Generate a daily summary of process accounting at 23:53
# 53 23 * * * root /usr/lib64/sa/sa2 -A
# 
#

- name: add sysstat cron job
  cron:
    name: sysstat_1
    minute: "*/5"
    user: root
    job: "/usr/lib64/sa/sa1 1 1"
    cron_file: sysstat

- name: add sysstat cron job
  cron:
    name: sysstat_2
    minute: "0"
    user: root
    job: "/usr/lib64/sa/sa1 600 6 &"
    cron_file: sysstat

- name: generate daily summary
  cron:
    name: sysstat_summary
    minute: "53"
    hour: "23"
    user: root
    job: "/usr/lib64/sa/sa2 -A"
    cron_file: sysstat
